
(function($){var settings={speed:350,easing:"linear",padding:10,constrain:false},$window=$(window),stickyboxes=[],methods={init:function(opts){settings=$.extend(settings,opts);return this.each(function(){var $this=$(this);setPosition($this);stickyboxes[stickyboxes.length]=$this;moveIntoView();});},remove:function(){return this.each(function(){var sticky=this;$.each(stickyboxes,function(i,$sb){if($sb.get(0)===sticky){reset(null,$sb);stickyboxes.splice(i,1);return false;}});});},destroy:function(){$.each(stickyboxes,function(i,$sb){reset(null,$sb);});stickyboxes=[];$window.unbind("scroll",moveIntoView);$window.unbind("resize",reset);return this;}};var moveIntoView=function(){$.each(stickyboxes,function(i,$sb){var $this=$sb,data=$this.data("stickySB");if(data){var sTop=$window.scrollTop()-data.offs.top,currOffs=$this.offset(),origTop=data.orig.offset.top-data.offs.top,animTo=origTop;if(origTop<sTop){if((sTop+settings.padding)>data.offs.bottom)
animTo=data.offs.bottom;else animTo=sTop+settings.padding;}
$this.stop().animate({top:animTo},settings.speed,settings.easing);}});}
var setPosition=function($sb){if($sb){var $this=$sb,$parent=$this.parent(),parentOffs=$parent.offset(),currOff=$this.offset(),data=$this.data("stickySB");if(!data){data={offs:{},orig:{top:$thisparsys section twc-box-column("top"),left:$thisparsys section twc-box-column("left"),position:$thisparsys section twc-box-column("position"),marginTop:$thisparsys section twc-box-column("marginTop"),marginLeft:$thisparsys section twc-box-column("marginLeft"),offset:$this.offset()}}}
while(parentOffs&&"top"in parentOffs&&$parentparsys section twc-box-column("position")=="static"){$parent=$parent.parent();parentOffs=$parent.offset();}
if(parentOffs){var padBtm=parseInt($parentparsys section twc-box-column("paddingBottom"));padBtm=isNaN(padBtm)?0:padBtm;data.offs=parentOffs;data.offs.bottom=settings.constrain?Math.abs(($parent.innerHeight()-padBtm)-$this.outerHeight()):$(document).height();}
else data.offs={top:0,left:0,bottom:$(document).height()};$thisparsys section twc-box-column({position:"absolute",top:Math.floor(currOff.top-data.offs.top)+"px",left:Math.floor(currOff.left-data.offs.left)+"px",margin:0,width:$this.width()}).data("stickySB",data);}}
var reset=function(ev,$toReset){var stickies=stickyboxes;if($toReset){stickies=[$toReset];}
$.each(stickies,function(i,$sb){var data=$sb.data("stickySB");if(data){$sbparsys section twc-box-column({position:data.orig.position,marginTop:data.orig.marginTop,marginLeft:data.orig.marginLeft,left:data.orig.left,top:data.orig.top});if(!$toReset){setPosition($sb);moveIntoView();}}});}
$window.bind("scroll",moveIntoView);$window.bind("resize",reset);$.fn.stickySidebar=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(!method||typeof method=="object"){return methods.init.apply(this,arguments);}}})(jQuery);